### ISSUE TITLE
Video player Facade

### ISSUE THREAD

**Issue by j4-m** [Cycling-UK/cycling-uk-application#19]
The homepage video is downloaded regardless of whether a user chooses to watch the video.

**Comment by j4-m** [comment]
I've tried to reproduce the above while investigating a fix but I haven't been able to so perhaps no further work required here.

**Comment by sachawellborn** [comment]
@alistair-martin @j4-m Does this only have to do with the home page video? If so, is it time to change the home page video so that its  hosted on youtube? That would make this task a moot point, right?

**Comment by alistair-martin** [comment]
Yes, the current home page video player was a workaround while we had the chicken and egg situation when the new website was first launched and we were trying to work out about YouTube playback when the user had not accepted cookies using the original cookie tools. Therefore, the home page video was self-hosted to bypass the YouTube aspect. This has now changed so your thinking about updating the home page video to be hosted on YouTube is valid.

**Comment by sachawellborn** [comment]
I've updated the home page video on develop to use a youtube video and amended the styling to make it fit in like the previous self hosted version.
